server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dinghong?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: DingHong@2026
    driver-class-name: com.mysql.cj.jdbc.Driver

# 顶红体育：The Odds API START
odds:
  api:
    enabled: true
    key: "24b4f41df3efc29a862dffdf3d4f3e0c"
    regions: "eu,uk,us"
    markets: "h2h,spreads,totals"
    oddsFormat: "decimal"
    footballSports: "soccer_epl,soccer_uefa_champs_league,soccer_japan_j_league,soccer_spain_la_liga,soccer_italy_serie_a,soccer_germany_bundesliga,soccer_france_ligue_one,soccer_uefa_europa_league,soccer_usa_mls,soccer_fifa_world_cup,soccer_fifa_world_cup_winner,soccer_uefa_euro_qualification,soccer_uefa_nations_league,soccer_conmebol_copa_libertadores,soccer_england_efl_championship,soccer_netherlands_eredivisie,soccer_portugal_primeira_liga"
    basketballSports: "basketball_nba,basketball_wnba,basketball_euroleague,basketball_ncaab,basketball_nbl,basketball_nba_summer_league"
# 顶红体育：The Odds API END
