-- 顶红公众号：文章草稿表

CREATE TABLE IF NOT EXISTS article_draft (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  match_id BIGINT UNSIGNED NOT NULL,
  data_json JSON NOT NULL,
  status ENUM('GENERATED','REVISED','PUBLISHED') NOT NULL DEFAULT 'GENERATED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_draft_match (match_id),
  KEY idx_draft_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
